### PR TITLE
[WIP] Update basemap

### LINKED ISSUE #8: Design basemap
Placeholder basemap style URL: mapbox://styles/nicki/cjav7yuqylrmk2speysk7tz9y

Notes on map features:
- Basemap can be minimal – just enough context for users to locate road corridors that they already know they want to propose as bike lanes
- Hide shared bike lanes and bus/bike lanes (currently dashed lines in placeholder style)
- Differentiate cycle tracks (currently blue line in placeholder style)
- Add [bike trail data](http://opendata.dc.gov/datasets/bike-trails) (and double if this includes NPS trails)

### PR DESCRIPTION
**Pull request by nickidlugash**
## Updates to base map

[Live link to map style](
https://api.mapbox.com/styles/v1/nicki/cjrfg5dvs73d42so15dr0qp5u.html?fresh=true&title=true&access_token=pk.eyJ1Ijoibmlja2kiLCJhIjoiczVvbFlXQSJ9.1Gegt3V_MTupW6wfjxq2QA#15.1/38.900883/-76.990337/0)

To see style in app, pull this branch and serve app locally. @WABA-Comms If it's easier, I can also merge this PR in first so that it gets published to the live app, if that's easier for you to review.

screen shot 2019-02-07 at 5 19 29 pm

### New Mapbox data and style syntax

I made a new base map using our recently released Light v10 style as a template. This style uses our latest data (Mapbox Streets v8 vector tiles) as well as some new Mapbox GL Style Spec syntax, so hopefully it will not need any updates for compatibility for a long time. 

### Updates based on previous feedback

Based on previous feedback in https://github.com/mapbox/waba-add-a-bike-lane/issues/8:

> Basemap can be minimal – just enough context for users to locate road corridors that they already know they want to propose as bike lanes

- Removed some non-road-related features: POI labels, water labels, waterway labels, hillshading, rail tracks, airport aeroways, and a few more very minor features.
- Removed all paths from Mapbox data (only visible "paths" are bike lanes or trails from DDOT data)
- Hid buildings until zoom level 16
- Hid very minor roads (like service roads and driveways) until z15

> Hide shared bike lanes and bus/bike lanes (currently dashed lines in placeholder style)

- Done.

> Differentiate cycle tracks (currently blue line in placeholder style)

- These are now the same color (blue) as the other bike lanes, but much thicker:

  screen shot 2019-02-07 at 5 20 07 pm

> Add [bike trail data](http://opendata.dc.gov/datasets/bike-trails) (and double if this includes NPS trails)

- Added these trails as green, dashed lines:

  screen shot 2019-02-07 at 5 20 17 pm

### Other updates

- Tweaked color scheme so that the land is pure grey, with a bit more color saturation in the park and water colors to help differentiate those. The bike lanes are now blue, and bike trails green. We'll probably want to tweak the colors of the proposed bike lane visualization based on these updates.
- Simplified some road styling, to make the map look cleaner.
- Greyed out motorway and trunk roads, so that it's more obvious that those roads cannot have bike lanes.

### Road and bike lane directionality

screen shot 2019-02-07 at 5 27 18 pm

@WABA-Comms Would love to get some feedback regarding visualization of oneway arrows. My assumption is that directionality of both existing bike lanes and roads are fairly important context. Right now, the directionality of roads are indicated by dark grey arrows, and the directionality of contraflow bike lanes are indicated by blue arrows (though if you have time to double-check that these are in fact the correct direction, I would appreciate it! My assumption was that the line geometries in the DDOT data are all in the direction of the bike lane's flow). Bike lanes directionality should therefore either be indicated by the grey arrow on that road, or a blue arrow if it's a contraflow lane. However, if a road has lanes in both directions, there won't be any arrows displayed. Is this ok? And in general, do you have any thoughts on if/how directionality can be made clearer?

### Feedback?

@WABA-Comms @peterqliu @k-mahoney Any other feedback would be appreciated!

TODO:
- [x] Make updates based on feedback
- [x] Change bike lane and trail data to be geojson rather than vector tiles
- [x] Update colors for proposed bike lane
- [x] Final code clean-up

Closes https://github.com/mapbox/waba-add-a-bike-lane/issues/8 https://github.com/mapbox/waba-add-a-bike-lane/issues/22

### CODE REVIEW

**Comment by peterqliu** [comment]
👍 looks good to me

**Comment by WABA-Comms** [comment]
Hey @nickidlugash I really like the basemap changes, and I think using line weight to differentiate between standard bike lanes and protected bike lanes works great. 

Two concerns about one-way arrows and contraflow lanes: the blue and the gray arrows are difficult to differentiate (to my slightly colorblind eyes). And just doing a quick spot check, it looks like the contraflow lanes on G Street NE are pointing the wrong way. Not sure if that's an underlying data problem or an issue with the bike lanes layer from DDOT.

**Comment by nickidlugash** [comment]
@WABA-Comms Sorry for the delayed response! Thanks for the helpful feedback regarding oneway arrows and contraflow lanes. 

For differentiation between blue and grey arrows, I can make the blue darker.

However, unfortunately I'm not sure how to resolve the issue of the incorrect contraflow lane arrow directions. My assumption initially was that the lines themselves were drawn in the direction of flow (such that if you were to draw an arrow pointing from the beginning of the line to the end of the line, that arrow would be in the correct direction of flow), but that seems not to be the case. From what I can tell, there is no correlation between the direction of the geometries and the direction of flow. There is a property for travel direction (with values of either `inbound` or `outbound` that seems to correspond to the direction of the car flow), but not all contraflow lanes have a value. Even if they did, I'm not sure how I would apply that data without consistent drawing of geometry direction.

I'm not that familiar with the ddot bike lane data though, so I may be missing something here. Please let me know if you have any suggestions! Otherwise, would it work to just label the contraflow lanes as "contraflow"?:

Screen Shot 2019-04-10 at 8 49 57 PM
Screen Shot 2019-04-10 at 8 49 50 PM

Another option that might look a bit cleaner could be to symbolize the contraflow lanes differently from other bike lanes. I tried using dashed (rather than solid) lines, but I was concerned that it wouldn't be readily apparently what the dashed lines meant. Is there a line styling option that you think would work well here?

Please let me know if you have a preferred option! Thanks!

**Comment by WABA-Comms** [comment]
I think labeling them as contraflow is a great solution, and seems like
it's probably the easiest to implement. Let's go with that!

Colin Browne
Communications Director
Washington Area Bicyclist Association
colinbrowne@waba.org
(202) 518-0524 x201
waba.org

Are you a card carrying WABA Member? Join or renew today
<http://waba.org/join>!

**Comment by nickidlugash** [comment]
@WABA-Comms Thanks for the feedback!

Other changes:

- Swapped out the vector tile bike lane and bike trail data for geojsons that get loaded at runtime. 
- Restyled the proposed bike lane, buffer and crash data to better match+contrast the new basemap. Also increased the buffer size, per https://github.com/mapbox/waba-add-a-bike-lane/issues/22:

  Screen Shot 2019-04-19 at 4 47 42 PM

@peterqliu If you have a chance to do a quick final review, that would be great 🙏 Otherwise I think this is probably fine to merge as-is.

@k-mahoney A few notes re: data scripting:
- I added the bike lane/trail geojsons to `/scripts/bike-lanes` / `/scripts/bike-trails` because that seemed to be the pattern, based on the collision data. Feel free to reorganize the data files and update the source paths.
- There are still 2 custom vector tile sources included in the style json (one for the speeding violations and one for the census data). When you swap these source definitions in app.js to use the downloaded geojsons, can you also please remove the custom sources from the style json? The style itself should then only include one source, Mapbox Streets v8.

**Review by peterqliu — APPROVED** [review]
looks good! 🚢

**Pull request merged**
